- name: Provision EC2 instance & install XX 
  hosts: localhost
  gather_facts: false
  roles:
    - ec2_launch


- name: Configuration of ec2 instances
  hosts: launched_ec2_instances
  gather_facts: true
  roles:
    - common

    