- name: Provision EC2 instance & install XX 
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Adding SSH access to a security group
      amazon.aws.ec2_group: 
        name: default
        description: Security group for EC2 instances
        region: us-east-1
        rules: 
          - proto: all
            from_port: 3001
            to_port: 3001
            cidr_ip: 0.0.0.0/0

          - proto: all
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0

          - proto: all
            from_port: 3000
            to_port: 3000
            cidr_ip: 0.0.0.0/0
          
          - proto: all
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0

        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
      register: security_group