---
name: Provision of Ec2 instance and configuration with Ansible 

on:
 push :
  branches: 
   - master

jobs:
  provision_ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with: # you can also use with:
          python-version: "3.10"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible boto3 requests
          ansible-galaxy collection install amazon.aws
          ansible-galaxy collection install community.docker --force
    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
    
      - name: Create SSH Key file
        run: |
         mkdir -p ~/.ssh
         echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/ec2_temp.pem
         chmod 600 ~/.ssh/ec2_temp.pem
       
      - name: Debug SSH key
        run: ls -l ~/.ssh/ec2_temp.pem

      - name: Run Ansible Playbook
        run: |
         ansible-playbook ./Ansible/playbooks/configure_provision_ec2_server.yml \
         -e "EC2_SSH_KEY_PATH=~/.ssh/ec2_temp.pem"
      
        env:
         ANSIBLE_HOST_KEY_CHECKING: false
    
    